a-romantic-cat/Back-end

.gitignore, build.gradle, src/main/resources/application.yml
환경 설정 변경
- 스프링 부트 버전 다운그레이드
- gitignore 설정
- db 정보 변경
=> 🔧 환경 설정 변경

build.gradle, src/main/java/aromanticcat/umcproject/config/SwaggerConfig.java
feat/10 -> dev
SwaggerConfig 파일 추가, dependency 추가
=> ✨Swagger 세팅

src/main/java/aromanticcat/umcproject/UmcProjectApplication.java, src/main/java/aromanticcat/umcproject/entity/BaseEntity.java, src/main/java/aromanticcat/umcproject/entity/Friend.java, src/main/java/aromanticcat/umcproject/entity/ItemBox.java, src/main/java/aromanticcat/umcproject/entity/Member.java, src/main/java/aromanticcat/umcproject/entity/MemberMission.java, src/main/java/aromanticcat/umcproject/entity/Mission.java, src/main/java/aromanticcat/umcproject/entity/NangmanLetter.java, src/main/java/aromanticcat/umcproject/entity/NangmanReply.java, src/main/java/aromanticcat/umcproject/entity/Reward.java, src/main/resources/application.yml
feat/10 -> dev
member, friend, mission, nangman 관련 entity를 추가했습니다.
=> ✨ entity 생성

src/main/java/aromanticcat/umcproject/entity/Member.java, src/main/java/aromanticcat/umcproject/entity/NangmanLetter.java
feat/14 -> dev
Member, NangmanLetter 엔티티에 어노테이션 추가했습니다.
=> :sparkles: Entity 어노테이션 추가

build.gradle, src/main/java/aromanticcat/umcproject/config/AppConfig.java, src/main/java/aromanticcat/umcproject/entity/Member.java, src/main/java/aromanticcat/umcproject/entity/NangmanLetter.java, src/test/java/aromanticcat/umcproject/repository/NangmanLetterRepositoryTests.java
feat/18 -> dev
낭만 우편함 편지 작성 테스트 메서드 추가
ModelMapper 설정
issue #18
=> ✨ ModelMapper 설정

src/main/java/aromanticcat/umcproject/converter/NangmanPostBoxConverter.java, src/main/java/aromanticcat/umcproject/repository/NangmanReplyRepository.java, src/main/java/aromanticcat/umcproject/service/NangmanPostBoxService.java, src/main/java/aromanticcat/umcproject/service/NangmanPostBoxServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanPostBoxController.java, src/main/java/aromanticcat/umcproject/web/dto/NangmanPostBoxRequestDTO.java, src/main/java/aromanticcat/umcproject/web/dto/NangmanPostBoxResponseDTO.java
=> ✨ 낭만우편함 답장 편지 발송 API 구현

src/main/java/aromanticcat/umcproject/converter/NangmanLetterBoxConverter.java, src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java
feat/34 -> dev
존재하는 사용자만 편지 작성 가능하도록 수정
이전 PR에 포함되어야 했을 commit..
성공
=> :sparkles: 존재하는 사용자만 편지 작성 가능하도록 수정

src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java, src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxService.java, src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java, src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxResponseDTO.java
feat/37 -> dev
현재 로그인된 사용자의 정보를 얻어오는 메서드는 임의로 구현 -> memberId = 1L 를 반환
성공
=> :sparkles: 낭만우편함 나의 편지 목록 조회 API 구현 (로그인된 사용자 정보 얻는 부분 제외)

.github/workflows/dev_deploy.yml, src/main/resources/application.yml
chore/4 -> dev
uses 설정 및 코드 수정
=> 🐛 uses 설정 및 코드 수정

.github/workflows/dev_deploy.yml
=> 🔧files 경로 수정

.github/workflows/dev_deploy.yml, .gitignore, src/main/resources/application.yml
chore/9 -> dev
application.yml 파일 gitignore 설정
=> 🔧 gitignore 설정

src/main/java/aromanticcat/umcproject/converter/NangmanLetterBoxConverter.java, src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java, src/main/java/aromanticcat/umcproject/repository/NangmanReplyRepository.java, src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxService.java, src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java, src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxResponseDTO.java
feat/39 -> dev
내가 쓴 편지에 대한 답장 조회하는 API 구현
성공
close #39
=> :sparkles: 내가 쓴 편지에 대한 답장 조회 API 구현

src/main/java/aromanticcat/umcproject/converter/NangmanLetterBoxConverter.java, src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java, src/main/java/aromanticcat/umcproject/service/NangmanCollectionService.java, src/main/java/aromanticcat/umcproject/service/NangmanCollectionServiceImpl.java, src/main/java/aromanticcat/umcproject/service/NangmanLetterBoxServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java, src/main/java/aromanticcat/umcproject/web/dto/NangmanCollection/NangmanCollectionResponseDTO.java, src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxResponseDTO.java
feat/58 -> dev
낭만모음집 목록 조회 API 구현
낭만우편함 내가 받은 답장 조회 -> 이모지 카운트 추가
성공
close #58
=> ✨ 낭만모음집 목록 조회 API

src/main/java/aromanticcat/umcproject/converter/NangmanLetterBoxConverter.java, src/main/java/aromanticcat/umcproject/entity/Member.java, src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java, src/main/java/aromanticcat/umcproject/repository/NangmanReplyRepository.java, src/main/java/aromanticcat/umcproject/service/NangmanCollectionService.java, src/main/java/aromanticcat/umcproject/service/NangmanCollectionServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java, src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxResponseDTO.java
feat/61 -> dev
낭만모음집 상세 조회 API 구현 완료
Member 엔티티 수정
성공
close #61
=> ✨ 낭만모음집 상세 조회 API 구현

src/main/java/aromanticcat/umcproject/entity/NangmanLetter.java, src/main/java/aromanticcat/umcproject/service/NangmanCollectionService.java, src/main/java/aromanticcat/umcproject/service/NangmanCollectionServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java
feat/63 -> dev
NangmanLetter 엔티티에 메서드 추가
좋아요 기능 구현
성공
close #63
=> ✨ 낭만모음집 좋아요 API 구현

src/main/java/aromanticcat/umcproject/converter/StoreConverter.java, src/main/java/aromanticcat/umcproject/entity/AcquiredItem.java, src/main/java/aromanticcat/umcproject/entity/ItemBox.java, src/main/java/aromanticcat/umcproject/entity/LetterPaper.java, src/main/java/aromanticcat/umcproject/entity/Member.java, src/main/java/aromanticcat/umcproject/entity/Stamp.java, src/main/java/aromanticcat/umcproject/repository/AcquiredItemRepository.java, src/main/java/aromanticcat/umcproject/repository/LetterPaperRepository.java, src/main/java/aromanticcat/umcproject/service/StoreService.java, src/main/java/aromanticcat/umcproject/service/StoreServiceImpl.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanCollectionService.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanCollectionServiceImpl.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanLetterBoxService.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanLetterBoxServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java, src/main/java/aromanticcat/umcproject/web/controller/StoreController.java, src/main/java/aromanticcat/umcproject/web/dto/NangmanCollection/NangmanCollectionResponseDTO.java, src/main/java/aromanticcat/umcproject/web/dto/store/StoreResponseDTO.java
feat/65 -> dev
상점에서 편지지 목록을 조회하는 API 구현
사용자가 이미 구매한 편지지는 가격 null 반환
성공
close #65
=> ✨ 상점 편지지 목록 조회 API 구현 완료

src/main/java/aromanticcat/umcproject/converter/StoreConverter.java, src/main/java/aromanticcat/umcproject/repository/StampRepository.java, src/main/java/aromanticcat/umcproject/service/StoreService.java, src/main/java/aromanticcat/umcproject/service/StoreServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/StoreController.java, src/main/java/aromanticcat/umcproject/web/dto/store/StoreResponseDTO.java
feat/67 -> dev
상점 우표 목록 조회 API 구현 완료
성공
=> :sparkles: 상점 우표 목록 조회 API 구현

src/main/java/aromanticcat/umcproject/converter/StoreConverter.java, src/main/java/aromanticcat/umcproject/entity/Member.java, src/main/java/aromanticcat/umcproject/repository/AcquiredItemRepository.java, src/main/java/aromanticcat/umcproject/service/StoreService.java, src/main/java/aromanticcat/umcproject/service/StoreServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/StoreController.java
feat/71 -> dev
편지지/우표 구매 API 구현 완료
Member 엔티티에 subtractCoin 메서드 추가
성공
=> ✨ 편지지/우표 구매 API

src/main/java/aromanticcat/umcproject/entity/Letter.java, src/main/java/aromanticcat/umcproject/entity/Letterbox.java, src/main/java/aromanticcat/umcproject/entity/Member.java, src/main/java/aromanticcat/umcproject/entity/Stamp.java, src/main/java/aromanticcat/umcproject/service/FriendService/FriendCommandServiceImpl.java
- [x ] 버그 수정
feat/78-> dev
우편함 엔티티 전반적 수정 및 오류 코드 수정
빌드 및 실행 확인 완료입니다.
=> Refactor/78 엔티티 수정 및 오류 해결

src/main/java/aromanticcat/umcproject/entity/Letterbox.java, src/main/java/aromanticcat/umcproject/repository/LetterBoxRepository.java, src/main/java/aromanticcat/umcproject/service/letterbox/LetterboxService.java, src/main/java/aromanticcat/umcproject/web/controller/LetterboxController.java, src/main/java/aromanticcat/umcproject/web/dto/LetterboxResponse.java
- [x ] 기능 추가
feat/29 -> dev
우편함 조회 기능 구현
빌드 실행 테스트 완료.
=> Feat/29 우편함 조회

src/main/java/aromanticcat/umcproject/entity/Letter.java, src/main/java/aromanticcat/umcproject/entity/LetterPaper.java, src/main/java/aromanticcat/umcproject/entity/Letterbox.java, src/main/java/aromanticcat/umcproject/repository/LetterPaperRepository.java, src/main/java/aromanticcat/umcproject/repository/LetterRepository.java, src/main/java/aromanticcat/umcproject/repository/StampRepository.java, src/main/java/aromanticcat/umcproject/service/letterbox/LetterService.java, src/main/java/aromanticcat/umcproject/service/letterbox/LetterboxService.java, src/main/java/aromanticcat/umcproject/web/controller/LetterController.java, src/main/java/aromanticcat/umcproject/web/controller/LetterboxController.java, src/main/java/aromanticcat/umcproject/web/dto/Letterbox/LetterRequest.java, src/main/java/aromanticcat/umcproject/web/dto/Letterbox/LetterResponse.java, src/main/java/aromanticcat/umcproject/web/dto/Letterbox/LetterboxRequest.java, src/main/java/aromanticcat/umcproject/web/dto/Letterbox/LetterboxResponse.java
ex) feat/76-> dev
편지 생성, 조회 API 구현
빌드, 실행, 테스트 완료
=> Feat/76 편지 생성, 조회 API

src/main/java/aromanticcat/umcproject/converter/MyCollectionConverter.java, src/main/java/aromanticcat/umcproject/converter/NangmanCollectionConverter.java, src/main/java/aromanticcat/umcproject/converter/NangmanLetterBoxConverter.java, src/main/java/aromanticcat/umcproject/entity/NangmanLetter.java, src/main/java/aromanticcat/umcproject/repository/AcquiredItemRepository.java, src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java, src/main/java/aromanticcat/umcproject/service/MyCollectionService.java, src/main/java/aromanticcat/umcproject/service/MyCollectionServiceImpl.java, src/main/java/aromanticcat/umcproject/service/StoreService.java, src/main/java/aromanticcat/umcproject/service/StoreServiceImpl.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/MyCollectionServiceImpl.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanCollectionService.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanCollectionServiceImpl.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanLetterBoxService.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/NangmanLetterBoxServiceImpl.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterBoxService/RandomNicknameService.java, src/main/java/aromanticcat/umcproject/web/controller/MyCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterBoxController.java, src/main/java/aromanticcat/umcproject/web/controller/StoreController.java, src/main/java/aromanticcat/umcproject/web/dto/MyCollectionResponseDTO.java, src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanCollectionResponseDTO.java, src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxRequestDTO.java, src/main/java/aromanticcat/umcproject/web/dto/nangmanLetterBox/NangmanLetterBoxResponseDTO.java
feat/73 -> dev
코드 리팩토링
낭만우편함 - 답장할 편지 목록에 내가 쓴 고민 편지는 안 보이도록 수정
성공
=> ♻️ 코드 리팩토링 + 낭만우편함 기능 수정

build.gradle, src/main/java/aromanticcat/umcproject/converter/MissionConverter.java, src/main/java/aromanticcat/umcproject/entity/Member.java, src/main/java/aromanticcat/umcproject/entity/MemberMission.java, src/main/java/aromanticcat/umcproject/entity/Mission.java, src/main/java/aromanticcat/umcproject/entity/MissionStatus.java, src/main/java/aromanticcat/umcproject/repository/MemberMissionRepository.java, src/main/java/aromanticcat/umcproject/repository/MissionRepository.java, src/main/java/aromanticcat/umcproject/service/MissionService/MissionCommandService.java, src/main/java/aromanticcat/umcproject/service/MissionService/MissionCommandServiceImpl.java, src/main/java/aromanticcat/umcproject/service/MissionService/MissionQueryService.java, src/main/java/aromanticcat/umcproject/service/MissionService/MissionQueryServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/FriendController.java, src/main/java/aromanticcat/umcproject/web/controller/MissionController.java, src/main/java/aromanticcat/umcproject/web/dto/Mission/MissionResponseDTO.java
- [✅] 기능 추가
ex) feat/31 -> dev
ex) 미션 관련 기능을 추가했습니다. (미션 목록 조회 API, 미션 상세 조회 API, 미션 단계 완료 API)
ex) feat/31 branch에서 정상적으로 작동하며, 스웨거에서 테스트한 결과 정상적으로 작동합니다.
=> feat: 미션 개발 완료

src/main/resources/application.yml
feat/92-> dev
S3 환경 변수 추가
테스트, 실행 확인 완료
=> ♻️  yml 환경 변수 추가

src/main/java/aromanticcat/umcproject/entity/Letter.java, src/main/java/aromanticcat/umcproject/repository/LetterBoxRepository.java, src/main/java/aromanticcat/umcproject/repository/LetterRepository.java, src/main/java/aromanticcat/umcproject/service/letterbox/LetterboxService.java, src/main/java/aromanticcat/umcproject/web/controller/LetterboxController.java, src/main/java/aromanticcat/umcproject/web/dto/Letterbox/LetterboxRequest.java
feat/77-> dev
지난 우편함, 활성화된 우편함, 우편함의 편지 리스트 조회 기능 구현 #77 
실행 확인 및 테스트 완료
=> Feat/77 우편함, 편지 리스트 조회 기능 구현 (#77)

src/main/resources/application.yml
feat/100 -> dev
환경 변수 이름 설정 방법 통일
=> 🔧 환경 변수 이름 설정 통일

src/main/java/aromanticcat/umcproject/repository/AcquiredItemRepository.java, src/main/java/aromanticcat/umcproject/repository/MyLetterPaperRepository.java, src/main/java/aromanticcat/umcproject/repository/MyStampRepository.java, src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java, src/main/java/aromanticcat/umcproject/repository/NangmanReplyRepository.java, src/main/java/aromanticcat/umcproject/service/myCollectionService/MyCollectionService.java, src/main/java/aromanticcat/umcproject/service/myCollectionService/MyCollectionServiceImpl.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanCollectionService.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanCollectionServiceImpl.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanLetterboxService.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanLetterboxServiceImpl.java, src/main/java/aromanticcat/umcproject/service/storeService/StoreService.java, src/main/java/aromanticcat/umcproject/service/storeService/StoreServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/MyCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterboxController.java, src/main/java/aromanticcat/umcproject/web/controller/StoreController.java
feat/102 -> dev
memberService.getUserInfo() 메서드 사용하도록 수정
소셜 로그인이라 스웨거에서 테스트 하지 못했음
=> :sparkles: 현재 로그인한 사용자 email 활용하도록 수정

src/main/java/aromanticcat/umcproject/converter/FriendConverter.java, src/main/java/aromanticcat/umcproject/entity/Friend.java, src/main/java/aromanticcat/umcproject/repository/FriendRepository.java, src/main/java/aromanticcat/umcproject/repository/MemberMissionRepository.java, src/main/java/aromanticcat/umcproject/service/FriendService/FriendCommandService.java, src/main/java/aromanticcat/umcproject/service/FriendService/FriendCommandServiceImpl.java, src/main/java/aromanticcat/umcproject/service/FriendService/FriendQueryService.java, src/main/java/aromanticcat/umcproject/service/FriendService/FriendQueryServiceImpl.java, src/main/java/aromanticcat/umcproject/service/MissionService/MissionCommandService.java, src/main/java/aromanticcat/umcproject/service/MissionService/MissionCommandServiceImpl.java, src/main/java/aromanticcat/umcproject/service/MissionService/MissionQueryService.java, src/main/java/aromanticcat/umcproject/service/MissionService/MissionQueryServiceImpl.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/RandomNicknameService.java, src/main/java/aromanticcat/umcproject/web/controller/FriendController.java, src/main/java/aromanticcat/umcproject/web/controller/MissionController.java, src/main/java/aromanticcat/umcproject/web/controller/StoreController.java
ex) feat/27 -> dev
ex) 미션, 주소록 사용자 임시 메서드에서 이메일로 접근하는 메서드로 바꿨습니다
ex) 스웨거에서 정상적으로 작동합니다
=> feat: 사용자 이메일로 접근

src/main/java/aromanticcat/umcproject/repository/LetterBoxRepository.java, src/main/java/aromanticcat/umcproject/repository/LetterRepository.java, src/main/java/aromanticcat/umcproject/service/letterbox/LetterboxService.java, src/main/java/aromanticcat/umcproject/web/controller/LetterboxController.java
feat/107-> dev
지난 우편함, 편지 리스트 조회 수정
정상 동작 확인 완료
=> :recycle: 지난 우편함, 편지 리스트 조회 수정

src/main/java/aromanticcat/umcproject/repository/MyLetterPaperRepository.java, src/main/java/aromanticcat/umcproject/repository/MyStampRepository.java, src/main/java/aromanticcat/umcproject/service/myCollectionService/MyDesignService.java, src/main/java/aromanticcat/umcproject/web/controller/MyDesignController.java, src/main/java/aromanticcat/umcproject/web/dto/MyDesign/MyDesignGetResponse.java, src/main/java/aromanticcat/umcproject/web/dto/MyDesign/MyDesignRequest.java
feat/110-> dev
마이디자인 조회 기능
테스트 정상 동작
=> :sparkles: 마이디자인 조회

src/main/java/aromanticcat/umcproject/entity/Friend.java, src/main/java/aromanticcat/umcproject/service/StampService.java, src/main/java/aromanticcat/umcproject/service/letterbox/LetterService.java, src/main/java/aromanticcat/umcproject/service/letterbox/LetterboxService.java, src/main/java/aromanticcat/umcproject/web/controller/LetterController.java, src/main/java/aromanticcat/umcproject/web/dto/Letterbox/LetterRequest.java
feat/112-> dev
친구 교환횟수 추가 기능 구현했습니다
정상 작동 확인
=> Refactor/#112 친구 교환횟수 추가 기능 구현

src/main/java/aromanticcat/umcproject/service/MemberService.java, src/main/java/aromanticcat/umcproject/service/MemberServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/MemberController.java
feat/114 -> dev
uri, 메서드 이름 변경
=> ♻️ 닉네임 변경 API

src/main/java/aromanticcat/umcproject/web/controller/AuthController.java, src/main/java/aromanticcat/umcproject/web/controller/FriendController.java, src/main/java/aromanticcat/umcproject/web/controller/LetterController.java, src/main/java/aromanticcat/umcproject/web/controller/LetterboxController.java, src/main/java/aromanticcat/umcproject/web/controller/MemberController.java, src/main/java/aromanticcat/umcproject/web/controller/MissionController.java, src/main/java/aromanticcat/umcproject/web/controller/MyCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/MyDesignController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterboxController.java, src/main/java/aromanticcat/umcproject/web/controller/RootController.java, src/main/java/aromanticcat/umcproject/web/controller/SlowLetterController.java, src/main/java/aromanticcat/umcproject/web/controller/StoreController.java
feat/116 -> dev
모든 컨트롤러에 
@CrossOrigin(origins = "https://dev.nangmancat.shop") 추가
auth, member 컨트롤러 @Operaiton -> @ApiOperation으로 변경
=> 🐛 cors에러, 운영 서버 스웨거 관련 코드 수정

src/main/java/aromanticcat/umcproject/web/controller/AuthController.java, src/main/java/aromanticcat/umcproject/web/controller/FriendController.java, src/main/java/aromanticcat/umcproject/web/controller/LetterController.java, src/main/java/aromanticcat/umcproject/web/controller/LetterboxController.java, src/main/java/aromanticcat/umcproject/web/controller/MemberController.java, src/main/java/aromanticcat/umcproject/web/controller/MissionController.java, src/main/java/aromanticcat/umcproject/web/controller/MyCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/MyDesignController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterboxController.java, src/main/java/aromanticcat/umcproject/web/controller/RootController.java, src/main/java/aromanticcat/umcproject/web/controller/SlowLetterController.java, src/main/java/aromanticcat/umcproject/web/controller/StoreController.java
=> cors 어노테이션 삭제

src/main/resources/application-app.yml, src/main/resources/application-oauth.yml, src/main/resources/application.yml
=> 🔧 환경 변수변경

src/main/java/aromanticcat/umcproject/web/dto/MemberRequestDTO.java
feat/124 -> dev
MemberRequestDTO 삭제
=> 🔥 MemberRequestDTO 삭제

src/main/java/aromanticcat/umcproject/security/SecurityConfig.java
=> 🐛 Security config 허용 uri 오타 수정

src/main/resources/application.yml
feat/127 -> dev
🔧 s3 bucket name 변경
=> 🔧 s3 bucket name 변경

src/main/resources/application.yml
=> 🔧 db 환경변수 변경

src/main/java/aromanticcat/umcproject/UmcProjectApplication.java
feat/141 -> dev
@SpringBootApplication에 exclude 추가
=> 🐛SdkClientException 해결

src/main/java/aromanticcat/umcproject/web/controller/AuthController.java, src/main/java/aromanticcat/umcproject/web/controller/FriendController.java, src/main/java/aromanticcat/umcproject/web/controller/MyCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/StoreController.java
=> :bug: 어노테이션 수정

src/main/resources/application.yml
feat/150 -> dev
로그인 시, 카카오 소셜 로그인 기능을 추가했습니다.
=> ✨ 카카오 소셜로그인 추가

src/main/java/aromanticcat/umcproject/config/WebMvcConfig.java
feat/152 -> dev
도메인 url에 포트번호:443 추가했습니다
=> 🐛 도메인 url 수정

src/main/java/aromanticcat/umcproject/security/SecurityConfig.java, src/main/java/aromanticcat/umcproject/web/controller/MemberController.java
feat/153 -> dev
membercontroller에 @corsorigin 적용했습니다
=> 🐛 corsorigin 적용

src/main/java/aromanticcat/umcproject/config/CorsConfig.java, src/main/java/aromanticcat/umcproject/config/WebMvcConfig.java, src/main/java/aromanticcat/umcproject/web/controller/MemberController.java
feat/155 -> dev
cors 이슈로 CorsConfig에 filter 작성하여 추가했습니다.
=> ✨ CorsConfig 추가

src/main/java/aromanticcat/umcproject/security/SecurityConfig.java
feat/157 -> dev
로그인 페이지 url이 https로 가도록 변경했습니다.
=> 🐛 로그인 페이지 url 변경

src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanCollectionService.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanCollectionServiceImpl.java, src/main/java/aromanticcat/umcproject/service/storeService/StoreService.java, src/main/java/aromanticcat/umcproject/service/storeService/StoreServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/MyCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/StoreController.java
=> ✨ 상점, 낭만모음집 정렬 기능 추가

src/main/java/aromanticcat/umcproject/config/SwaggerConfig.java
feat/163 -> dev
swagger 시큐리티 적용 삭제
=> ♻️ swagger 시큐리티 적용 삭제

src/main/java/aromanticcat/umcproject/repository/FriendRepository.java
=> friend repository 수정

src/main/java/aromanticcat/umcproject/converter/MemberConverter.java, src/main/java/aromanticcat/umcproject/service/MemberService.java, src/main/java/aromanticcat/umcproject/service/MemberServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/FriendController.java, src/main/java/aromanticcat/umcproject/web/controller/MemberController.java, src/main/java/aromanticcat/umcproject/web/dto/Member/MemberRequestDTO.java, src/main/java/aromanticcat/umcproject/web/dto/Member/MemberResponseDTO.java
=> feat: 사용자 검색 API 추가

src/main/java/aromanticcat/umcproject/entity/LetterPaper.java, src/main/java/aromanticcat/umcproject/entity/Stamp.java, src/main/java/aromanticcat/umcproject/repository/NangmanLetterRepository.java, src/main/java/aromanticcat/umcproject/service/myCollectionService/MyCollectionService.java, src/main/java/aromanticcat/umcproject/service/myCollectionService/MyCollectionServiceImpl.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanCollectionService.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanCollectionServiceImpl.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanLetterboxService.java, src/main/java/aromanticcat/umcproject/service/nangmanLetterboxService/NangmanLetterboxServiceImpl.java, src/main/java/aromanticcat/umcproject/service/storeService/StoreService.java, src/main/java/aromanticcat/umcproject/service/storeService/StoreServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/MyCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterboxController.java, src/main/java/aromanticcat/umcproject/web/controller/StoreController.java
=> ✨ 페이지 정보 추가, 상점 아이템 업로드 API 추가, 코인 조회 추가

src/main/java/aromanticcat/umcproject/security/SecurityConfig.java, src/main/java/aromanticcat/umcproject/security/oauth/MyAuthenticationSuccessHandler.java
feat/176 -> dev
uri 변경, token 쿼리 전달
=> 🐛 uri 변경, token 쿼리 전달

src/main/java/aromanticcat/umcproject/S3/S3Service.java
=> :bug: s3 url 변경

src/main/java/aromanticcat/umcproject/security/SecurityConfig.java, src/main/java/aromanticcat/umcproject/security/oauth/MyAuthenticationFailureHandler.java, src/main/java/aromanticcat/umcproject/security/oauth/MyAuthenticationSuccessHandler.java
feat/177 -> dev
oauth2 redirect uri loalhost:3000으로 변경
=> 🐛 oauth2 redirect uri

src/main/java/aromanticcat/umcproject/S3/S3Service.java
=> :white_check_mark: s3 test

src/main/java/aromanticcat/umcproject/converter/MissionConverter.java, src/main/java/aromanticcat/umcproject/entity/Mission.java, src/main/java/aromanticcat/umcproject/web/dto/Mission/MissionResponseDTO.java
=> feat: 미션에 매일 속성 추가

src/main/java/aromanticcat/umcproject/security/SecurityConfig.java, src/main/java/aromanticcat/umcproject/security/oauth/MyAuthenticationFailureHandler.java, src/main/java/aromanticcat/umcproject/security/oauth/MyAuthenticationSuccessHandler.java, src/main/java/aromanticcat/umcproject/web/controller/MemberController.java
=> 🐛 oauth2 uri, 회원가입 api 수정

src/main/java/aromanticcat/umcproject/entity/MemberMission.java, src/main/java/aromanticcat/umcproject/entity/Mission.java, src/main/java/aromanticcat/umcproject/service/FriendService/FriendCommandService.java, src/main/java/aromanticcat/umcproject/service/FriendService/FriendCommandServiceImpl.java, src/main/java/aromanticcat/umcproject/service/MissionService/MissionCommandService.java, src/main/java/aromanticcat/umcproject/service/MissionService/MissionCommandServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/FriendController.java
=> feat: 친한 친구 해제 API 추가

src/main/java/aromanticcat/umcproject/web/controller/SlowLetterController.java
=> :recycle: 스웨거 api설명 추가

src/main/resources/application.yml
=> 🐛 oauth2 redirect-uri 변경

src/main/java/aromanticcat/umcproject/security/SecurityConfig.java
=> 🐛 허용가능 uri 변경

src/main/java/aromanticcat/umcproject/service/MemberService.java, src/main/java/aromanticcat/umcproject/service/MemberServiceImpl.java, src/main/java/aromanticcat/umcproject/service/MissionService/MissionCommandServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/FriendController.java, src/main/java/aromanticcat/umcproject/web/dto/Member/MemberResponseDTO.java
=> feat: 매일 자정 초기화 메서드 삭제

src/main/java/aromanticcat/umcproject/service/MemberService.java, src/main/java/aromanticcat/umcproject/service/MissionService/MissionCommandService.java
=> bug: 오류 수정

src/main/java/aromanticcat/umcproject/repository/LetterRepository.java, src/main/java/aromanticcat/umcproject/service/letterbox/LetterboxService.java, src/main/java/aromanticcat/umcproject/web/controller/LetterboxController.java
=> :sparkles: open된 편지 리스트 조회

build.gradle, src/main/java/aromanticcat/umcproject/config/SecurityConfig.java, src/main/java/aromanticcat/umcproject/config/SwaggerConfig.java, src/main/java/aromanticcat/umcproject/entity/Member.java, src/main/java/aromanticcat/umcproject/entity/Role.java, src/main/java/aromanticcat/umcproject/jwt/CustomUserDetailService.java, src/main/java/aromanticcat/umcproject/jwt/JwtAuthenticationFilter.java, src/main/java/aromanticcat/umcproject/jwt/JwtTokenProvider.java, src/main/java/aromanticcat/umcproject/jwt/SecurityUtil.java, src/main/java/aromanticcat/umcproject/repository/AcquiredItemRepository.java, src/main/java/aromanticcat/umcproject/repository/MyLetterPaperRepository.java, src/main/java/aromanticcat/umcproject/repository/MyStampRepository.java, src/main/java/aromanticcat/umcproject/service/MemberService.java, src/main/java/aromanticcat/umcproject/service/MemberServiceImpl.java, src/main/java/aromanticcat/umcproject/service/myCollectionService/MyCollectionService.java, src/main/java/aromanticcat/umcproject/service/myCollectionService/MyCollectionServiceImpl.java, src/main/java/aromanticcat/umcproject/web/controller/FriendController.java, src/main/java/aromanticcat/umcproject/web/controller/MemberApiController.java, src/main/java/aromanticcat/umcproject/web/controller/MissionController.java, src/main/java/aromanticcat/umcproject/web/controller/MyCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanCollectionController.java, src/main/java/aromanticcat/umcproject/web/controller/NangmanLetterboxController.java, src/main/java/aromanticcat/umcproject/web/controller/StoreController.java, src/main/java/aromanticcat/umcproject/web/dto/Member/MemberSignInRequestDto.java, src/main/java/aromanticcat/umcproject/web/dto/Member/MemberSignupRequestDto.java, src/main/java/aromanticcat/umcproject/web/dto/Member/MemberSignupResponseDto.java, src/main/java/aromanticcat/umcproject/web/dto/Member/TokenResponseDto.java, src/main/resources/application.yml
feat/193 -> dev
(소셜x)로그인 구현, 시큐리티 코드 수정
성공
=> :sparkles: Security, Swagger 설정 수정, 일반 로그인 구현 완료
